sudo: false
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - expect
language: node_js
node_js:
  - 6
  - 8
  - 10

before_install:
# Get installer script.
  - wget https://raw.githubusercontent.com/nodeGame/nodegame/master/bin/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
# Make this nodegame-window available to nodeGame.
# Old phantomjs has no "unsafe access" warning bug.
# Disregard that; only newer phantomjs works with node v0.12.
 #- npm install 'phantomjs@<1.9.8'
  - npm install --only=dev
  ## --branch v4
  - node nodegame-installer.js @dev --install-dir node_modules --no-spinner --yes
# To test specific branch add: --branch branchName
# Install tester game.
  - git clone https://github.com/nodeGame/testergame node_modules/nodegame/games/testergame
#before_script:
# Link testing directory into game.
  - cd node_modules/nodegame/games/testergame/public
  - ln -s ../../../../../test test
  - ls -la test/
  - ln -s ../../../../../node_modules node_modules
  - ls -la node_modules/
  - cd ../../../../../
# Add servernode conf file (to increase verbosity)
  - ln -sf test/servernode.conf.js node_modules/nodegame/conf/servernode.js

script:
  - expect test/runtest.exp

# Test Ultimatum game.
  - cd node_modules/nodegame/games/ultimatum-game
  - ./bin/run-standalone-test-v4.sh
