sudo: false
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - expect
language: node_js
node_js:
  - 8

before_install:
# Get installer script.
  - wget https://github.com/nodeGame/nodegame-test/raw/master/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
# Make this nodegame-window available to nodeGame.
# Old phantomjs has no "unsafe access" warning bug.
# Disregard that; only newer phantomjs works with node v0.12.
  #- npm install 'phantomjs@<1.9.8'
   - npm install --only=dev
   - node nodegame-installer.js @dev --install-dir node_modules --no-spinner --branch v4 --yes

# Install tester game.
  - git clone https://github.com/nodeGame/testergame node_modules/nodegame/games/testergame
#before_script:
# Link testing directory into game.
  - cd nodegame/games/testergame/public
# Add servernode conf file (to increase verbosity)
  - ln -sf test/servernode.conf.js node_modules/nodegame/conf/servernode.js

script:
  - expect test/runtest.exp

# Test Ultimatum game.
  - cd node_modules/nodegame/games/ultimatum-game
  - ./bin/run-standalone-test-v4.sh
